CRM/urls.py
from django.contrib import admin
from django.urls import path,include
from stark.service.stark import site

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rbac/',include('rbac.urls',namespace='rbac')),
    path('',include('management.urls')),
    path('stark/',site.urls)
]

rbac/service/urls.py
from django.urls import reverse
from django.http import QueryDict
"""
保留原搜索条件的url以及解析原搜索条件

"""


def memory(request,name,*args,**kwargs):
    """
    生成带有原搜索条件的URL
    记忆上次访问状态
    :return:
    """
    basic_url = reverse(name,args=args,kwargs=kwargs)

    # 当前url中没有参数
    if not request.GET:
        return basic_url

    query_dict = QueryDict(mutable=True)
    query_dict['_filter'] = request.GET.urlencode()
    return "%s?%s"%(basic_url,query_dict.urlencode())


def memory_reverse(request,name,*args,**kwargs):
    """
    反向生成url
        - 在url中将原来的搜索条件获取
        - reverse生成原来的url，如/menu/menu_list
        - 拼接_filter的值
    :param request:
    :param name:
    :param args:
    :param kwargs:
    :return:
    """
    url = reverse(name,args=args,kwargs=kwargs)
    orgin_params = request.GET.get('_filter')
    if orgin_params:
        url = "%s?%s" % (url, orgin_params)
    return url

rbac/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from rbac.views import role
from rbac.views import user
from rbac.views import menu
app_name='rbac'
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('role/list/',role.role_list,name='role_list'),
    path('role/add/',role.role_add,name='role_add'),
    url(r'^role/edit/(?P<num>\d+)/$',role.role_edit,name='role_edit'),
    url(r'^role/del/(?P<num>\d+)/$',role.role_del,name='role_del'),


        # path('user/list/',user.user_list,name='user_list'),
        # path('user/add/',user.user_add,name='user_add'),
        # url(r'^user/edit/(?P<num>\d+)/$',user.user_edit,name='user_edit'),
        # url(r'^user/del/(?P<num>\d+)/$',user.user_del,name='user_del'),
        # url(r'^user/reset_password/(?P<num>\d+)/$',user.reset_password,name='user_reset'),

    path('menu/list/',menu.menu_list,name='menu_list'),
    path('menu/menu_add/',menu.menu_add,name='menu_add'),
    url(r'^menu/del/(?P<num>\d+)/',menu.menu_del,name='menu_del'),
    url(r'^menu/edit/(?P<num>\d+)/',menu.menu_edit,name='menu_edit'),

    url(r'^second/second_add/(?P<num>\d+)/$', menu.second_menu_add, name='second_menu_add'),
    url(r'^second/del/(?P<num>\d+)/$', menu.second_menu_del, name='second_menu_del'),
    url(r'^second/edit/(?P<num>\d+)/$', menu.second_menu_edit, name='second_menu_edit'),

    url(r'^permission/add/(?P<second_id>\d+)/$', menu.permission_add,name='permission_add'),
    url(r'^permission/del/(?P<second_id>\d+)/$', menu.permission_del,name='permission_del'),
    url(r'^permission/edit/(?P<second_id>\d+)/$', menu.permission_edit,name='permission_edit'),

    # 批量操作

    path('multi/permission/',menu.multi_permission,name='multi_permission'),
    url(r'^multi/permission/del/(?P<id>\d+)/$',menu.multi_permission_del,name='multi_permission_del'),

    # 分配权限
    path('distribute/permission',menu.distribute_permission,name='distribute_permission')


]

rbac/forms/base.py
from django import forms

class BaseModelForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        """
        统一给ModelForm字段构建样式
        :param args:
        :param kwargs:
        """
        super(BaseModelForm, self).__init__(*args,**kwargs)
        for name,field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['style'] = 'margin-top:10px'

rbac/views/menu.py
from django.shortcuts import render, redirect, HttpResponse
from rbac.forms.menu import MenuModelForm, SecondMenuModelForm, PermissionModelForm, UpdatePermissionForm, \
    MultiAddPermissionForm
from rbac import models
from rbac.service.urls import memory_reverse
from django.forms import formset_factory
from rbac.service.get_url import get_all_url_dict
from collections import OrderedDict
from django.urls import reverse
from django.utils.module_loading import import_string
from django.conf import settings


def menu_list(request):
    """
    菜单和权限列表
    :param request:
    :return:
    """
    menu = models.Menu.objects.all()
    if not request.GET:
        return render(request, 'rbac/menu_list.html', {'menus': menu})
    mid = request.GET.get('mid')
    if mid:
        second_menu = models.Permission.objects.filter(menu_id=mid)

        second_id = request.GET.get('sid')
        if second_id:
            # 如果前端传过来的sid存在的话
            # http://127.0.0.1:8000/rbac/menu/list/?mid=1&sid=1
            permission_list = models.Permission.objects.filter(pid=second_id)

            # 判断前端传过来的second_id是否存在，如果不存在则不显示新增按钮
            second_list = models.Permission.objects.filter(id=second_id)
            if not second_list:
                second_id = 0
            return render(request, 'rbac/menu_list.html',
                          {
                              'menus': menu,
                              'menu_id': int(mid),
                              'second_menu': second_menu,
                              'sid': int(second_id),
                              'permission_list': permission_list
                          })
        return render(request, 'rbac/menu_list.html',
                      {
                          'menus': menu,
                          'menu_id': int(mid),
                          'second_menu': second_menu,
                      })
    return render(request, 'rbac/menu_list.html', {'menus': menu})


def menu_add(request):
    """
    添加一级菜单
    :param request:
    :return:
    """
    if request.method == 'POST':
        form = MenuModelForm(request.POST)
        if form.is_valid():
            form.save()
            url = memory_reverse(request, 'rbac:menu_list')
            return redirect(url)
        else:
            return render(request, 'rbac/change.html', {'form': form})
    form = MenuModelForm()
    return render(request, 'rbac/change.html', {'form': form})


def menu_del(request, num):
    url = memory_reverse(request, 'rbac:menu_list')

    if request.method == 'GET':
        role = models.Menu.objects.filter(id=num).first()
        return render(request, 'rbac/delete.html', {'role': role, 'cancel': url})
    models.Menu.objects.filter(id=num).delete()
    return redirect(url)


def menu_edit(request, num):
    """
    一级菜单删除
    :param request:
    :param num:
    :return:
    """
    obj = models.Menu.objects.filter(pk=num)
    url = memory_reverse(request, 'rbac:menu_list')
    if not obj.first():
        response = HttpResponse('角色不存在')
        response.status_code = 404
        return response
    if request.method == 'GET':
        form = MenuModelForm(instance=obj.first())
        return render(request, 'rbac/change.html', {'form': form})

    form = MenuModelForm(instance=obj.first(), data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(url)
    return render(request, 'rbac/change.html', {'form': form})


def second_menu_add(request, num):
    """
    添加二级菜单
    :param request:
    :param menu_id: 已选择的一级菜单ID（用于设置默认选中）
    :return:
    """
    menu_obj = models.Menu.objects.filter(id=num).first()
    if request.method == 'POST':
        form = SecondMenuModelForm(request.POST)
        if form.is_valid():
            form.save()
            url = memory_reverse(request, 'rbac:menu_list')
            return redirect(url)
        else:
            return render(request, 'rbac/change.html', {'form': form})
    form = SecondMenuModelForm(initial={'menu': menu_obj})
    return render(request, 'rbac/change.html', {'form': form})


def second_menu_del(request, num):
    url = memory_reverse(request, 'rbac:menu_list')

    if request.method == 'GET':
        return render(request, 'rbac/delete.html', {'cancel': url})
    models.Permission.objects.filter(id=num).delete()
    return redirect(url)


def second_menu_edit(request, num):
    obj = models.Permission.objects.filter(pk=num)
    url = memory_reverse(request, 'rbac:menu_list')
    if not obj.first():
        response = HttpResponse('角色不存在')
        response.status_code = 404
        return response
    if request.method == 'GET':
        form = SecondMenuModelForm(instance=obj.first())
        return render(request, 'rbac/change.html', {'form': form})

    form = SecondMenuModelForm(instance=obj.first(), data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(url)
    return render(request, 'rbac/change.html', {'form': form})


def permission_add(request, second_id):
    """
    添加权限
    :param request:
    :param second_id:
    :return:
    """
    if request.method == 'POST':
        form = PermissionModelForm(request.POST)
        if form.is_valid():
            second_menu_obj = models.Permission.objects.filter(id=second_id).first()
            if not second_menu_obj:
                return HttpResponse('二级菜单不存在，请重新选择')
            # form.instance中包含用户提交的所有值,相当于写了下面两段代码
            # instance = models.Permission(title='',name='',url='')
            # instance.id = second_menu_obj
            form.instance.pid = second_menu_obj
            form.save()
            url = memory_reverse(request, 'rbac:menu_list')
            return redirect(url)
        else:
            return render(request, 'rbac/change.html', {'form': form})
    form = PermissionModelForm()
    return render(request, 'rbac/change.html', {'form': form})


def permission_del(request, second_id):
    url = memory_reverse(request, 'rbac:menu_list')

    if request.method == 'GET':
        return render(request, 'rbac/delete.html', {'cancel': url})
    models.Permission.objects.filter(id=second_id).delete()
    return redirect(url)


def permission_edit(request, second_id):
    obj = models.Permission.objects.filter(pk=second_id)
    url = memory_reverse(request, 'rbac:menu_list')
    if not obj.first():
        response = HttpResponse('角色不存在')
        response.status_code = 404
        return response
    if request.method == 'GET':
        form = PermissionModelForm(instance=obj.first())
        return render(request, 'rbac/change.html', {'form': form})

    form = PermissionModelForm(instance=obj.first(), data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(url)
    return render(request, 'rbac/change.html', {'form': form})


#
# def permission_batch_add(request):
#     # 先实例出formset对象，参数一是需要渲染的ModelForm,第二个参数是需要增加多少个
#     form_class = formset_factory(BatchPermissionModelForm, extra=2)
#
#     if request.method == 'POST':
#         # post请求，提交数据
#         formset = form_class(data=request.POST)  # 把接受到的数据放到formset中
#         if formset.is_valid():  # 使用formset表单进行验证
#             post_data = formset.cleaned_data  # 先取出验证成功后的数据
#             flag = True
#             for i in range(0, formset.total_form_count()):  # 循环
#                 # 检测保存时是否会出现错误，如果出现错误捕获错误放到errors中再在页面中渲染出来
#                 row_data = post_data[i]
#                 if not row_data:
#                     continue
#                 try:
#                     print(row_data)
#                     obj = models.Permission(**row_data)
#                     obj.validate_unique()
#                     # obj.save()
#                 except Exception as e:
#                     formset.errors[i].update(e)
#                     flag = False
#             if flag:
#                 return HttpResponse('增加成功')
#             else:
#                 render(request, 'rbac/multi_permission.html', {'formset': formset})
#         else:
#             render(request, 'rbac/multi_permission.html', {'formset': formset})
#
#     # get请求页面，将需要渲染的form表单传到模板，在模板中渲染
#     formset = form_class()
#     return render(request, 'rbac/multi_permission.html', {'formset': formset})


def multi_permission(request):
    """
    批量操作权限:获取项目中所有的URL
    :param request:
    :return:
    """
    post_type = request.GET.get('type')

    generate_formset_class = formset_factory(MultiAddPermissionForm, extra=0)
    update_formset_class = formset_factory(UpdatePermissionForm, extra=0)
    generate_formset = None
    update_formset = None
    if request.method == 'POST' and post_type == 'generate':
        # 批量添加
        formset = generate_formset_class(data=request.POST)
        if formset.is_valid():
            post_row_list = formset.cleaned_data

            # 用于批量增加
            object_list = []
            has_errors = False
            for i in range(0, formset.total_form_count()):
                row_dict = post_row_list[i]
                try:
                    new_obj = models.Permission(**row_dict)
                    new_obj.validate_unique()
                    object_list.append(new_obj)
                except Exception as e:
                    formset.errors[i].update(e)
                    generate_formset = formset
                    has_errors = True
            if not has_errors:  # 如果新添加的数据没有错误，就写入数据库
                models.Permission.objects.bulk_create(object_list, batch_size=100)
        else:
            generate_formset = formset

    if request.method == 'POST' and post_type == 'update':
        # 批量更新
        formset = update_formset_class(data=request.POST)
        if formset.is_valid():
            post_row_list = formset.cleaned_data
            for i in range(0, formset.total_form_count()):
                row_dict = post_row_list[i]
                # 取出id，根据id更改数据库中的数据
                permission_id = row_dict.pop('id')
                try:

rbac/views/role.py
"""
角色管理
"""
from django.shortcuts import render,redirect,HttpResponse
from rbac import models
from rbac.forms.role import RoleModelForm
from django.urls import reverse




def role_list(request):
    """
    角色列表
    :param request:
    :return:
    """
    role_queryset = models.Role.objects.all()
    return render(request, 'rbac/role_list.html', {'roles':role_queryset})


def role_add(request):
    """
    添加角色
    :param request:
    :return:
    """

    if request.method =='POST':
        form = RoleModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('rbac:role_list'))
        else:
            return render(request, 'rbac/change.html', {'form': form})
    form = RoleModelForm()
    return render(request, 'rbac/change.html', {'form':form})

def role_edit(request,num):
    """
    更改角色
    :param request:
    :param num:
    :return:
    """
    obj = models.Role.objects.filter(pk=num)
    if not obj.first():
        response = HttpResponse('角色不存在')
        response.status_code = 404
        return response
    if request.method =='GET':
        form = RoleModelForm(instance=obj.first())
        return render(request, 'rbac/change.html', {'form':form})

    form = RoleModelForm(instance=obj.first(),data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:role_list'))
    return render(request, 'rbac/change.html', {'form': form})


def role_del(request,num):
    """
    删除角色
    :param request:
    :param num:
    :return:
    """
    origin_url = reverse('rbac:role_list')
    if request.method == 'GET':
        role = models.Role.objects.filter(id=num).first()
        return render(request,'rbac/delete.html',{'role':role,'cancel':origin_url})
    models.Role.objects.filter(id=num).delete()
    return redirect(origin_url)

rbac/views/user.py
from django.shortcuts import redirect,HttpResponse,render
from django.urls import reverse
from rbac.models import UserInfo
from rbac.forms.user import UserModelForm,UpdateUserModelForm,ResetPasswordModelForm

def user_list(request):
    """
    用户列表
    :param request:
    :return:
    """
    users = UserInfo.objects.all()

    return render(request,'rbac/user_List.html',{'users':users})



def user_add(request):
    """
    新增用户
    :param request:
    :return:
    """
    if request.method =='GET':
        form = UserModelForm()
        return render(request,'rbac/change.html',{'form':form})
    form = UserModelForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:user_list'))
    return render(request,'rbac/change.html',{'form':form})

def user_edit(request,num):
    """
    编辑用户
    :param request:
    :param num:
    :return:
    """
    obj = UserInfo.objects.filter(id=num)
    if not obj.first():
        return HttpResponse('用户不存在')

    if request.method =='GET':
        form = UpdateUserModelForm(instance=obj.first())
        return render(request,'rbac/change.html',{'form':form})

    form = UpdateUserModelForm(instance=obj.first(),data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('rbac:user_list'))
    return render(request,'rbac/change.html',{'form':form})


def user_del(request,num):
    """
    删除用户
    :param request:
    :param num:
    :return:
    """
    cancel = reverse('rbac:user_list')
    if request.method == 'GET':
        return render(request,'rbac/delete.html',{'cancel':cancel})

    UserInfo.objects.filter(id=num).delete()
    return redirect(cancel)

def reset_password(request,num):
    """
    重置密码
    :param request:
    :param num:
    :return:
    """
    obj = UserInfo.objects.filter(id=num)
    if request.method =='POST':
        form = ResetPasswordModelForm(instance=obj.first(),data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('rbac:user_list'))
        else:
            return render(request, 'rbac/change.html', {'form': form})
    form = ResetPasswordModelForm()
    return render(request,'rbac/change.html',{'form':form})

rbac/templates/rbac/change.html
{% extends 'rbac/layout.html' %}

{% block css %}
    <style>
        ul{
            list-style-type: none;
            padding:0 ;
            }
        ul li{
            float: left;
            padding: 10px;
            padding-left: 0;
            width: 80px;
        }
        ul li i{
            font-size: 18px;
            margin-left: 5px;
            color: #6d6565;
        }
    </style>
{% endblock %}

{% block content %}

    <form action="" method="post" style="margin-top: 10px;margin-left: 10px" >
        {% csrf_token %}

        {% for field in form %}
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="tiele" class="control-label">
                            {{ field.label }}
                        </label>
                        <span style="color:red">{{ field.errors.0 }}</span>
                        <div>
                            {{ field }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

        <input type="submit" class="btn btn-success" value="保存">
    </form>


{% endblock %}

rbac/templates/rbac/delete.html
{% extends 'rbac/layout.html' %}



{% block content %}
    <form action="" method="post">
        {% csrf_token %}

        <div class="alert alert-danger" role="alert" style="margin: 20px;">
            <h3><i class="fa fa-warning"></i>你确定要删除吗，删除后不可恢复</h3>
            <br>
            <div class="form-group">
                <a href="{{ cancel }}" class="btn btn-default">取消</a>
                <input type="submit" value="确认" class="btn btn-danger">
            </div>

        </div>

    </form>
{% endblock %}

rbac/templates/rbac/menu_list.html
{% extends 'rbac/layout.html' %}
{% load rbac %}
{% block css %}
    <style>
        .active {
            border-left: 3px solid #f0ad4e;
            border-radius: 5px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="luffy-container">
        <div class="row">
            <div class="col-md-3 ">
                <div class="bs-example" data-example-id="table-within-panel">
                    <div class="panel panel-default ">
                        <!-- Default panel contents -->
                        <div class="panel-heading clearfix">
                            <i class="fa fa-book"></i>&nbsp;<strong>一级菜单</strong>
                            <a href="{% memory_url request 'rbac:menu_add'%}" class="btn btn-success pull-right "><i
                                    class="fa fa-pencil"></i>&nbsp;新增</a>
                        </div>

                        <!-- Table -->
                        <table class="table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>名称</th>
                                <th>图标</th>
                                <th>选项</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for menu in menus %}
                                <tr class="{% if menu.id == menu_id %}active{% endif %}">
                                    <th scope="row">{{ forloop.counter }}</th>
                                    <td><a href="?mid={{ menu.id }}">{{ menu.title }}</a></td>
                                    <td><i class="{{ menu.icon }}"></i></td>
                                    <td>
                                        <a href="{% memory_url request 'rbac:menu_edit' menu.id %}"><i
                                                class="fa fa-edit"></i></a>
                                        |
                                        <a href="{% memory_url request 'rbac:menu_del' menu.id %}" style="color: red"><i
                                                class="fa fa-minus-square"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                {% if request.GET %}
                    <div class="bs-example" data-example-id="table-within-panel">
                        <div class="panel panel-default ">
                            <!-- Default panel contents -->
                            <div class="panel-heading clearfix">
                                <i class="fa fa-code"></i>&nbsp;<strong>二级菜单</strong>
                                <a href="{% memory_url request 'rbac:second_menu_add' num=menu_id %}"
                                   class="btn btn-success pull-right "><i class="fa fa-pencil"></i>&nbsp;新增</a>
                            </div>

                            <!-- Table -->

                            <table class="table">
                                <thead>
                                <tr>
                                    <th>名称</th>
                                    <th>CODE&URL</th>
                                    <th>选项</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% for second in second_menu %}
                                    <tr class="{% if sid == second.id %}active{% endif %}">
                                        <th><a href="?mid={{ menu_id }}&sid={{ second.id }}">{{ second.title }}</a></th>
                                        <th>
                                            {{ second.name }}
                                            <br>
                                            <br>
                                            {{ second.url }}
                                        </th>
                                        <th>
                                            <a href="{% memory_url request 'rbac:second_menu_edit' num=second.id %}"><i class="fa fa-edit"></i></a>
                                            |
                                            <a href="{% memory_url request 'rbac:second_menu_del' num=second.id %}" style="color: red"><i class="fa fa-minus-square"></i></a>
                                        </th>

                                    </tr>

                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                {% endif %}


            </div>
            <div class="col-lg-5">
                {% if request.GET %}
                    <div class="bs-example" data-example-id="table-within-panel">
                        <div class="panel panel-default ">
                            <!-- Default panel contents -->
                            <div class="panel-heading clearfix">
                                <i class="fa fa-bars"></i>&nbsp;<strong>权限菜单</strong>
                                {% if sid %}
                                <a href="{% memory_url request 'rbac:permission_add' second_id=sid %}" class="btn btn-success pull-right "><i class="fa fa-pencil"></i>&nbsp;新增</a>
                                {% endif %}
                                <a href="{% url 'rbac:multi_permission' %}" class="btn btn-primary pull-right">批量操作</a>

                            </div>

                            <!-- Table -->

                            <table class="table">
                                <thead>
                                <tr>
                                    <th>名称</th>
                                    <th>CODE&URL</th>
                                    <th>选项</th>

                                </tr>
                                </thead>
                                <tbody>
                                {% for permission in permission_list %}
                                    <tr>
                                        <th>{{ permission.title }}</th>
                                        <th>
                                            {{ permission.name }}
                                            <br>
                                            <br>
                                            {{ permission.url }}
                                        </th>
                                        <th>
                                            <a href="{% memory_url request 'rbac:permission_edit' second_id=permission.id %}"><i class="fa fa-edit"></i></a>
                                            |
                                            <a href="{% memory_url request 'rbac:permission_del' second_id=permission.id %}" style="color: red"><i class="fa fa-minus-square"></i></a>
                                        </th>

                                    </tr>

                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                {% endif %}


            </div>


        </div>
    </div>

{% endblock %}

rbac/templates/rbac/multi_menu.html
{% for menu in menu_dict.values %}
    <div class="item">
        <div class="title">
            <a href="JavaScript:;" class="stair_menu">
                <span class="icon-wrap"><i class="{{ menu.icon }}"></i></span>{{ menu.title }}</a>
        </div>
        <div class="{{ menu.class }}">
            {% for item in menu.children %}
                    <a href="{{ item.url }}" class="second_menu {{ item.class }}">{{ item.title }}</a>

            {% endfor %}
        </div>
    </div>

{% endfor %}

rbac/templates/rbac/record.html
<div>
    <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">
        {% for item in record %}
            {% if item.class %}
                <li class="{{ item.class }}">{{ item.title }}</li>
            {% else %}
                <li><a href="{{ item.url }}">{{ item.title }}</a></li>
            {% endif %}
        {% endfor %}
    </ol>
</div>

rbac/templates/rbac/role_list.html
{% extends 'rbac/layout.html' %}


{% block content %}

{#    <div class="row" style="margin-top: 10px">#}
{#        <div class="col-lg-4">#}
{#            <div class="panel panel-primary">#}
{#        <div class="panel-heading">角色列表 <a href="#" class="btn-sm btn-success pull-right">添加角色</a></div>#}
{#        <div class="panel-body">#}
{#            <table class="table table-bordered table-striped">#}
{#                <thead>#}
{#                <tr>#}
{#                    <th>id</th>#}
{#                    <th>职位名称</th>#}
{#                </tr>#}
{#                </thead>#}
{#                <tbody>#}
{#                {% for role in roles %}#}
{#                    <tr>#}
{#                        <td>{{ role.id }}</td>#}
{#                        <td>{{ role.title }}</td>#}
{#                    </tr>#}
{##}
{#                {% endfor %}#}
{##}
{#                </tbody>#}
{#            </table>#}
{#        </div>#}
{#    </div>#}
{#        </div>#}
{##}
{#    </div>#}
    <div class="luffy-container">
        <div class="btn-group" style="margin: 5px 0">
                <a class="btn btn-default" href="{% url 'rbac:role_add' %}">
                    <i class="fa fa-file-excel-o" aria-hidden="true"></i> 添加角色
                </a>

        </div>
         <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>id</th>
                    <th>职位名称</th>
                    <th>选项</th>
                </tr>
                </thead>
                <tbody>
                {% for role in roles %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ role.title }}</td>
                        <td>
                            <a href="{% url 'rbac:role_edit' num=role.id %}" class="btn btn-info">
                                <i class="fa fa-sun-o" aria-hidden="true"></i>&nbsp;编辑</a>
                            <a href="{% url 'rbac:role_del' num=role.id %}" class="btn btn-success">
                                <i class="fa fa-remove" aria-hidden="true"></i>&nbsp;删除</a>
                        </td>
                    </tr>

                {% endfor %}

                </tbody>
            </table>
    </div>

{% endblock %}

rbac/templates/rbac/static_menu.html
{% for menu in menu_list %}
    {% if path_info == menu.url %}
    <a href="{{ menu.url }}" class="active">
        <span class="icon-wrap"><i class="{{ menu.icon }}"></i></span>{{ menu.title }}</a>
       {% else %}
        <a href="{{ menu.url }}">
        <span class="icon-wrap"><i class="{{ menu.icon }}"></i></span>{{ menu.title }}</a>
    {% endif %}
    

{% endfor %}